# Step: caddy - Caddy reverse proxy as a container, plus the /srv directory layout.
#
#   /srv/static/<hostname>/      static sites (served by the catch-all below)
#   /srv/docker/<name>/          Docker apps (compose projects)
#   /srv/data/<name>/            persistent app data (never touched by deploys)
#   /srv/vps/                    vpsctl state: generated Caddy routes, password hashes, compose overrides
#   /srv/vps/caddy/              the Caddy container itself (managed by this step)

CADDY_DIR=/srv/vps/caddy

step_caddy() {
  command -v docker >/dev/null || die "Docker is not installed. Run the 'docker' step first."

  log "Creating /srv layout"
  install -d -m 755 -o "$VPS_USER" -g "$VPS_USER" /srv/static /srv/docker /srv/data /srv/vps /srv/vps/overrides
  install -d -m 700 -o "$VPS_USER" -g "$VPS_USER" /srv/vps/auth
  install -d -m 755 -o root -g root "$CADDY_DIR" "$CADDY_DIR/etc"
  install -d -m 755 -o "$VPS_USER" -g "$VPS_USER" "$CADDY_DIR/etc/sites"

  log "Configuring Caddy"
  write_caddyfile
  local caddyfile_changed=$WRITE_FILE_CHANGED

  write_file "$CADDY_DIR/compose.yaml" <<EOF
$MANAGED_HEADER
name: caddy

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./etc:/etc/caddy:ro
      - /srv/static:/srv/static:ro
      - data:/data
      - config:/config
    networks:
      - caddy

networks:
  caddy:
    external: true

volumes:
  data:
  config:
EOF

  docker compose -f "$CADDY_DIR/compose.yaml" up -d

  # A running container doesn't notice a changed Caddyfile on its own.
  if $caddyfile_changed; then
    local i
    for i in {1..10}; do
      if docker exec caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile &>/dev/null; then
        info "Caddy config reloaded"
        return 0
      fi
      sleep 1
    done
    die "Caddy did not accept the new Caddyfile. Check: docker logs caddy"
  fi
}

write_caddyfile() {
  local email_line=""
  if [[ -n $ACME_EMAIL ]]; then
    email_line=$'\temail '"$ACME_EMAIL"$'\n'
  fi

  write_file "$CADDY_DIR/etc/Caddyfile" <<EOF
$MANAGED_HEADER
# Per-app routes are generated by vpsctl into sites/ - see bin/vpsctl.
{
${email_line}	# Certificates for static sites are requested on their first visit, but only
	# for hostnames that have a folder in /srv/static (checked by :9123 below).
	on_demand_tls {
		ask http://127.0.0.1:9123/check
	}
}

# Serves a static site folder. Used by the catch-all and by password-protected sites.
(static_files) {
	root * {args[0]}

	# Never serve dotfiles (.env, .git, ...), except .well-known.
	@hidden {
		path */.*
		not path /.well-known/*
	}
	respond @hidden 404

	# Paths without a file extension that don't exist fall back to /index.html,
	# so client-side routing in single-page apps works.
	@spa {
		not path_regexp \.[A-Za-z0-9]+$
		not file {path} {path}/
	}
	rewrite @spa /index.html

	encode zstd gzip
	file_server
}

# Routes for Docker apps and password-protected static sites (generated by vpsctl).
import sites/*.caddy

# Internal: approves on-demand certificates for hostnames with a static site.
:9123 {
	bind 127.0.0.1
	@site {
		expression \`{query.domain}.matches("^[a-z0-9-]+([.][a-z0-9-]+)+$")\`
		file {
			root /srv/static
			try_files {query.domain}/
		}
	}
	respond @site 200
	respond 404
}

# Catch-all: any other hostname is served from /srv/static/<hostname>/ if it exists.
https:// {
	tls {
		on_demand
	}

	@site {
		# Strict hostname check, so the Host header can't point root outside /srv/static.
		expression \`{host}.matches("^[a-z0-9-]+([.][a-z0-9-]+)+$")\`
		file {
			root /srv/static
			try_files {host}/
		}
	}
	handle @site {
		import static_files /srv/static/{host}
	}
	handle {
		respond "Not found" 404
	}
}

http:// {
	redir https://{host}{uri} permanent
}
EOF
}
